//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	config "sigs.k8s.io/scheduler-plugins/pkg/apis/config"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*NetworkBandwidthArgs)(nil), (*config.NetworkBandwidthArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NetworkBandwidthArgs_To_config_NetworkBandwidthArgs(a.(*NetworkBandwidthArgs), b.(*config.NetworkBandwidthArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.NetworkBandwidthArgs)(nil), (*NetworkBandwidthArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_NetworkBandwidthArgs_To_v1beta1_NetworkBandwidthArgs(a.(*config.NetworkBandwidthArgs), b.(*NetworkBandwidthArgs), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_NetworkBandwidthArgs_To_config_NetworkBandwidthArgs(in *NetworkBandwidthArgs, out *config.NetworkBandwidthArgs, s conversion.Scope) error {
	if err := v1.Convert_Pointer_string_To_string(&in.Address, &out.Address, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_string_To_string(&in.NetworkInterface, &out.NetworkInterface, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_int64_To_int64(&in.TimeRangeInMinutes, &out.TimeRangeInMinutes, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_NetworkBandwidthArgs_To_config_NetworkBandwidthArgs is an autogenerated conversion function.
func Convert_v1beta1_NetworkBandwidthArgs_To_config_NetworkBandwidthArgs(in *NetworkBandwidthArgs, out *config.NetworkBandwidthArgs, s conversion.Scope) error {
	return autoConvert_v1beta1_NetworkBandwidthArgs_To_config_NetworkBandwidthArgs(in, out, s)
}

func autoConvert_config_NetworkBandwidthArgs_To_v1beta1_NetworkBandwidthArgs(in *config.NetworkBandwidthArgs, out *NetworkBandwidthArgs, s conversion.Scope) error {
	if err := v1.Convert_string_To_Pointer_string(&in.Address, &out.Address, s); err != nil {
		return err
	}
	if err := v1.Convert_string_To_Pointer_string(&in.NetworkInterface, &out.NetworkInterface, s); err != nil {
		return err
	}
	if err := v1.Convert_int64_To_Pointer_int64(&in.TimeRangeInMinutes, &out.TimeRangeInMinutes, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_NetworkBandwidthArgs_To_v1beta1_NetworkBandwidthArgs is an autogenerated conversion function.
func Convert_config_NetworkBandwidthArgs_To_v1beta1_NetworkBandwidthArgs(in *config.NetworkBandwidthArgs, out *NetworkBandwidthArgs, s conversion.Scope) error {
	return autoConvert_config_NetworkBandwidthArgs_To_v1beta1_NetworkBandwidthArgs(in, out, s)
}
